(defun simple-equal (x y)
  (if (or (atom x) (atom y))
	(eql x y)
	(and (simple-equal (car x) (car y))
		 (simple-equal (cdr x) (cdr y)))))

(defun pat-match (pattern input)
  (if (variable-p pattern)
	t
	(if (or (atom pattern ) (atom input))
	  (eql pattern input)
	  (and (pat-match (car pattern) (car input))
		   (pat-match (cdr pattern) (cdr input))))))

(defun variable-p (x)
  (and (symbolp x) (equal (char (symbol-name x) 0) #\?)))

(defconstant fail nil)
(defconstant no-bindings '((t . t)))

(defun get-binding (var bindings)
  (assoc var bindings))

(defun binding-val (binding)
  (cdr binding))

(defun lookup (var bindings)
  (binding-val (get-binding var bindings)))

(defun extend-bindings (var val bindings)
  (cons (cons var val) bindings))

(defun pat-match (pattern input &optional (bindings no-bindings))
  (cond ((eq bindings fail) fail)
		((variable-p pattern)
		 (match-variable pattern input bindings))
		((eql pattern input) bindings)
		((and (consp pattern) (consp input))
		 (pat-match (cdr pattern) (cdr input)
					(pat-match (car pattern) (car input) bindings)))
		(t fail)))

(defun match-variable (var input bindings)
  (let ((binding (get-binding var bindings)))
	(cond ((not binding) (extend-bindings var input bindings))
		  ((equal input (binding-val binding)) bindings)
		  (t fail))))


(defun extend-bindings (var val bindings)
  (cons (cons var val)
		(if (eq bindings no-bindings)
		  nil
		  bindings)))

(defun pat-match (pattern input &optional (bindings no-bindings))
  (cond ((eq bindings fail) fail)
		((variable-p pattern) 
		 (match-variable pattern input bindings))
		((eql pattern input) bindings)
		((segment-pattern-p pattern)
		 (segment-match pattern input bindings))
		((and (consp pattern) (consp input))
		 (pat-match (cdr pattern) (cdr input)
					(pat-match (car pattern) (car input) bindings)))
		(t fail)))

(defun segment-pattern-p (pattern)
  (and (consp pattern)
	   (starts-with (car pattern) '?*)))

(defun starts-with (lst symb)
  (if (consp lst)
	(eql (car lst) symb)
	(eql lst symb)))

(defun segment-match (pattern input bindings &optional (start 0))
  (let ((var (cadr (car pattern)))
		(pat (cdr pattern)))
	(if (null pat)
	  (match-variable var input bindings)
	  (let ((pos (position (car pat) input :start start :test #'equal)))
		(if (null pos)
		  fail
		  (let ((b2 (pat-match pat (subseq input pos) bindings)))
			(if (eq b2 fail)
			  (segment-match pattern input bindings (1+ pos))
			  (match-variable var (subseq input 0 pos) b2))))))))

(defun segment-match (pattern input bindings &optional (start 0))
  (let ((var (cadr (car pattern)))
		(pat (cdr pattern)))
	(if (null pat)
	  (match-variable var input bindings)
	  (let ((pos (position (car pat) input :start start :test #'equal)))
		(if (null pos)
		  fail
		  (let ((b2 (pat-match
					  pat (subseq input pos)
					  (match-variable var (subseq input 0 pos)
									  bindings))))
			(if (eq b2 fail)
			  (segment-match pattern input bindings (1+ pos))
			  b2)))))))

(defun rule-pattern (rule) (car rule))
(defun rule-responses (rule) (cdr rule))

(defparameter *eliza-rules* 
 '((((?* ?x) ola (?* ?y)) ;;;;;;;;;;;;;;; SAUDAÇÕES
    (Como voce vai?Qual sua dificuldade no curso? Relacionamento? Disciplina? Saude Mental? Trabalho? Campus?))
   (((?* ?x) oi (?* ?y))
    (Como voce vai?Qual seu problema no curso? Relacionamento? Disciplina? Saude Mental? Trabalho? Campus?))
   
   (((?* ?x) estou (?* ?y)) ;;;;;;;;;;;;;;; ESTADO
    (Como voce esta?))     
   (((?* ?x) (eu estou triste) (?* ?y))
    (Qual disciplina que te deixa triste?))
   (((?* ?x) (eu estou estressado) (?* ?y))
    (Qual disciplina que te deixa estressado?))
   (((?* ?x) (eu estou zangado) (?* ?y))
    (Qual disciplina que te deixa zangado?))
   (((?* ?x) (eu estou cansado) (?* ?y))
    (Qual disciplina que te deixa cansado?))
   (((?* ?x) (eu estou estressada) (?* ?y))
    (Qual disciplina que te deixa estressada?))
   (((?* ?x) (eu estou zangado) (?* ?y))
    (Qual disciplina que te deixa zangada?))
   (((?* ?x) (eu estou cansado) (?* ?y))
    (Qual disciplina que te deixa cansada?))
   
   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
   (((?* ?x) disciplina (?* ?y)) ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; BLOCO DISCIPLINA @CAIOFROTA
     (de qual disciplina voce quer falar?))
   (((?* ?x) arquitetura (?* ?y))
     (Interessante! Voce gosta ou nao gosta dessa disciplina?))
   (((?* ?x) paradigmas (?* ?y))
     (Uau. Eh gracas a ela que estou aqui nesse momento. Voce gosta ou nao gosta dessa disciplina?))
   (((?* ?x) eletronica (?* ?y))
     (Xiiii... Uma disciplina de 96 horas. Deve ser bastante cansativo. Voce gosta ou nao gosta da disciplina?))
   (((?* ?x) (eletronica digital) (?* ?y))
   	 (Xiiii... Uma disciplina de 96 horas. Deve ser bastante cansativo. Voce gosta ou nao gosta da disciplina?))
    (((?* ?x) (circuitos eletricos) (?* ?y))
     (Xiiii... Uma disciplina de 96 horas. Deve ser bastante cansativo. Voce gosta ou nao gosta da disciplina?))
   (((?* ?x) circuitos (?* ?y))
     (Xiiii... Uma disciplina de 96 horas. Deve ser bastante cansativo. Voce gosta ou nao gosta da disciplina?))
   (((?* ?x) (eletromagnetismo aplicado) (?* ?y))
     (Xiiii... Uma disciplina de 96 horas. Deve ser bastante cansativo. Voce gosta ou nao gosta da disciplina?))
   (((?* ?x) eletromagnetismo (?* ?y))
     (Xiiii... Uma disciplina de 96 horas. Deve ser bastante cansativo. Voce gosta ou nao gosta da disciplina?))
   (((?* ?x) eletromag (?* ?y))
     (Xiiii... Uma disciplina de 96 horas. Deve ser bastante cansativo. Voce gosta ou nao gosta da disciplina?))
   (((?* ?x) (calculo 1) (?* ?y))
     (Humm. Interessante! Voce gosta ou nao gosta da disciplina?))
   (((?* ?x) (calculo 2) (?* ?y))
     (Humm. Interessante! Voce gosta ou nao gosta da disciplina?))
   (((?* ?x) (calculo vetorial) (?* ?y))
     (Humm. Interessante! Voce gosta ou nao gosta da disciplina?))
   (((?* ?x) calculo (?* ?y))
     (Humm. Interessante! Voce gosta ou nao gosta da disciplina?))
   (((?* ?x) (fisica 1) (?* ?y))
     (Humm. Interessante! Voce gosta ou nao gosta da disciplina?))
   (((?* ?x) (fisica 2) (?* ?y))
     (Humm. Interessante! Voce gosta ou nao gosta da disciplina?))
   (((?* ?x) (fisica 3) (?* ?y))
     (Humm. Interessante! Voce gosta da disciplina ou nao gosta da disciplina?))
   (((?* ?x) fisica (?* ?y))
     (Humm. Interessante! Voce gosta ou nao gosta da disciplina?))
                ;;;;;; CASO A RESPOSTA SEJA "NAO GOSTO"
   (((?* ?x) (nao gosto da disciplina) (?* ?y))     
     (Serio? Isso se deve ao que? O que lhe incomoda? O conteudo? O professor? As provas? ))     ;;BLOCO DISCIPLINA
   (((?* ?x) (n gosto da disciplina) (?* ?y))
   	 (Serio? Isso se deve ao que? O que lhe incomoda? O conteudo? O professor? As provas? ))
   (((?* ?x) (eu n gosto da disciplina) (?* ?y))
     (Serio? Isso se deve ao que? O que lhe incomoda? O conteudo? O professor? As provas? ))
   (((?* ?x) (eu nao gosto da disciplina) (?* ?y))
     (Serio? Isso se deve ao que? O que lhe incomoda? O conteudo? O professor? As provas? ))
          ;;;;;;;; CONTEUDO
   (((?* ?x) (O conteudo) (?* ?y))
     (Voce gosta do conteudo ou nao gosta do conteudo?)
     (Nao se preocupe busque ajuda de amigos e estude frequentemente que isso deixara de ser um problema rsrs))     ;;BLOCO DISCIPLINA
   (((?* ?x) conteudo (?* ?y))
     (Voce gosta do conteudo ou nao gosta do conteudo?)
     (Nao se preocupe busque ajuda de amigos e estude frequentemente que isso deixara de ser um problema rsrs))
   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
   (((?* ?x) (gosto do conteudo) (?* ?y))
     (Gostar do conteudo eh um bom comeco para se dar bem e ter facilidade nela. Nao esqueca que ha amigos que nao tem a mesma facilidade ajude o proximo))
   (((?* ?x) (eu gosto do conteudo) (?* ?y))
     (Gostar do conteudo eh um bom comeco para se dar bem e ter facilidade nela. Nao esqueca que ha amigos que nao tem a mesma facilidade ajude o proximo))
   (((?* ?x) (nao gosto do conteudo) (?* ?y))
     (Nao se preocupe busque ajuda de amigos e estude frequentemente que isso deixara de ser um problema rsrs))
   (((?* ?x) (eu nao gosto do conteudo) (?* ?y))
     (Nao se preocupe busque ajuda de amigos e estude frequentemente que isso deixara de ser um problema rsrs))
   (((?* ?x) (eu n gosto do conteudo) (?* ?y))
     (Nao se preocupe busque ajuda de amigos e estude frequentemente que isso deixara de ser um problema rsrs))
   (((?* ?x) (n gosto do conteudo) (?* ?y))
     (Nao se preocupe busque ajuda de amigos e estude frequentemente que isso deixara de ser um problema rsrs))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;; PROFESSOR
   (((?* ?x) (o professor) (?* ?y))
     (Voce admira o professor ou nao admira? )
     (Nooossa me conta mais. Porque voce acha isso? Porque ele eh chato? Porque ele eh rigido? Ou porque ele eh preguicoso?))
  (((?* ?x) professor (?* ?y))
     (Voce admira o professor ou nao admira? )
     (Nooossa me conta mais. Porque voce acha isso? Porque ele eh chato? Porque ele eh rigido? Ou porque ele eh preguicoso?))
  (((?* ?x) (ao professor) (?* ?y))
     (Voce admira o professor ou nao admira?))

  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  (((?* ?x) (eu admiro o professor) (?* ?y))
     (Que maximo! O que lhe chama a atencao nele? A inteligencia? A gentileza? Ou a dedicacao ?))
  (((?* ?x) (admiro o professor) (?* ?y))
     (Que maximo! O que lhe chama a atencao nele? A inteligencia? A gentileza? Ou a dedicacao ?))
  (((?* ?x) (eu nao admiro o professor) (?* ?y))
     (Nooossa me conta mais. Porque voce acha isso? Porque ele eh chato? Porque ele eh rigido? Ou porque ele eh preguicoso?))
  (((?* ?x) (nao admiro o professor) (?* ?y))
     (Nooossa me conta mais. Porque voce acha isso? Porque ele eh chato? Porque ele eh rigido? Ou porque ele eh preguicoso?))
  (((?* ?x) (eu n admiro o professor) (?* ?y))
     (Nooossa me conta mais. Porque voce acha isso? Porque ele eh chato? Porque ele eh rigido? Ou porque ele eh preguicoso?))
  (((?* ?x) (n admiro o professor) (?* ?y))
     (Nooossa me conta mais. Porque voce acha isso? Porque ele eh chato? Porque ele eh rigido? Ou porque ele eh preguicoso?))
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  (((?* ?x) (A inteligencia) (?* ?y))
     (Toop! Professores inteligentes sempre sao admirados pelos alunos. Continue sobre o que lhe incomoda na faculdade ))
  (((?* ?x) (A gentileza) (?* ?y))
     (Que bom! Afinal ser gentil eh o primeiro passo de um professor ter uma boa relacao com seus alunos.Continue sobre o que lhe incomoda na faculdade))
  (((?* ?x) (A dedicacao) (?* ?y))
     (Com um professor dedicado fica mais facil se interessar pela disciplina. Que otimo!!!Continue sobre o que lhe incomoda na faculdade))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    ;;;;;; PROVAS
   (((?* ?x) provas (?* ?y))
     (O que voce acha do nivel das provas?))     
   (((?* ?x) (as provas) (?* ?y))
     (O que voce acha do nivel das provas?))
   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
   (((?* ?x) (acho dificil) (?* ?y))
     (Talvez voce tenha um pouco de dificuldade em aprender o conteudo. Peca ajuda a seus amigos. O importante eh nao desistir))
   (((?* ?x) (eu acho dificil) (?* ?y))
     (Talvez voce tenha um pouco de dificuldade em aprender o conteudo. Peca ajuda a seus amigos. O importante eh nao desistir))
   (((?* ?x) dificil (?* ?y))
     (Talvez voce tenha um pouco de dificuldade em aprender o conteudo. Peca ajuda a seus amigos. O importante eh nao desistir))
   (((?* ?x) (muito dificil) (?* ?y))
     (Talvez voce tenha um pouco de dificuldade em aprender o conteudo. Peca ajuda a seus amigos. O importante eh nao desistir))
   (((?* ?x) (eu acho muito dificil) (?* ?y))
     (Talvez voce tenha um pouco de dificuldade em aprender o conteudo. Peca ajuda a seus amigos. O importante eh nao desistir))
   (((?* ?x) (mt dificil) (?* ?y))
     (Talvez voce tenha um pouco de dificuldade em aprender o conteudo. Peca ajuda a seus amigos. O importante eh nao desistir))
   (((?* ?x) (eu acho mt dificil) (?* ?y))
     (Talvez voce tenha um pouco de dificuldade em aprender o conteudo. Peca ajuda a seus amigos. O importante eh nao desistir))
   (((?* ?x) (mais ou menos) (?* ?y))
     (Legal. Continue assim que no final da certo))
   (((?* ?x) (acho facil) (?* ?y))
     (Que bom! Parece que voce tem mais facilidade em aprender o conteudo. Ajude seus amigos que tem dificuldade. Afinal gentileza gera gentileza))
   (((?* ?x) (eu acho facil) (?* ?y))
     (Que bom! Parece que voce tem mais facilidade em aprender o conteudo. Ajude seus amigos que tem dificuldade. Afinal gentileza gera gentileza))
   (((?* ?x) (muito facil) (?* ?y))
     (Que bom! Parece que voce tem mais facilidade em aprender o conteudo. Ajude seus amigos que tem dificuldade. Afinal gentileza gera gentileza))
   (((?* ?x) (eu acho muito facil) (?* ?y))
     (Que bom! Parece que voce tem mais facilidade em aprender o conteudo. Ajude seus amigos que tem dificuldade. Afinal gentileza gera gentileza))
   (((?* ?x) (mt facil) (?* ?y))
     (Que bom! Parece que voce tem mais facilidade em aprender o conteudo. Ajude seus amigos que tem dificuldade. Afinal gentileza gera gentileza))
   (((?* ?x) (eu acho mt facil) (?* ?y))
     (Que bom! Parece que voce tem mais facilidade em aprender o conteudo. Ajude seus amigos que tem dificuldade. Afinal gentileza gera gentileza))
   (((?* ?x) (very easy) (?* ?y))
     (Que bom! Parece que voce tem mais facilidade em aprender o conteudo. Ajude seus amigos que tem dificuldade. Afinal gentileza gera gentileza))
   (((?* ?x) facil (?* ?y))
     (Que bom! Parece que voce tem mais facilidade em aprender o conteudo. Ajude seus amigos que tem dificuldade. Afinal gentileza gera gentileza))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
   ;;;;;;;;;;;;;;;;;; CASO A RESPOSTA SEJA "GOSTO"
   (((?* ?x) (gosto da disciplina) (?* ?y))     
     (Serio? Que incrivel! Isso se deve ao que? O que mais lhe agrada na disciplina? O conteudo? O professor? As provas?))
   (((?* ?x) (eu gosto da disciplina) (?* ?y))     
     (Serio? Que incrivel! Isso se deve ao que? O que mais lhe agrada na disciplina? O conteudo? O professor? As provas?))
   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
   ;;;;;;;;;;; PALAVROES
   (((?* ?x) palavrao (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) cu (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) (vai da o cu) (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) fdp (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) rola (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) mp (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) (meu pau) (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) (filha da puta) (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) (fi de puta) (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) (fi duma egua) (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) (filho de uma egua) (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) (filho de uma egua) (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) arrombado (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) (professor eh arrombado) (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) (o professor eh um arrombado) (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) priquito (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) xana (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) vagina (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) cuzao (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) gostosa (?* ?y))
     (Isso eh assedio e posso lhe denunciar. Cuidado e mais respeito!!!))
   (((?* ?x) punheta (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) masturbacao (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) (filha da puta) (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) (fi de puta) (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) (filho de uma quenga) (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) piroca (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) (pega no meu pau) (?* ?y))
     (Isso eh assedio e posso lhe denunciar. Cuidado e mais respeito!!!))
   (((?* ?x) (chupa aqui) (?* ?y))
     (Isso eh assedio e posso lhe denunciar. Cuidado e mais respeito!!!))
   (((?* ?x) (oh la em casa) (?* ?y))
     (Isso eh assedio e posso lhe denunciar. Cuidado e mais respeito!!! E essa cantada foi horrivel rsrs...))
   (((?* ?x) foda (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) (vai se fuder) (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   (((?* ?x) (nossa que peitos) (?* ?y))
     (Isso eh assedio e posso lhe denunciar. Cuidado e mais respeito!!!))
   (((?* ?x) (nossa que peitoes) (?* ?y))
     (Isso eh assedio e posso lhe denunciar. Cuidado e mais respeito!!!))
   (((?* ?x) (que bunda linda) (?* ?y))
     (Isso eh assedio e posso lhe denunciar. Cuidado e mais respeito!!!))
   (((?* ?x) (vamos fuder) (?* ?y))
     (Isso eh assedio e posso lhe denunciar. Cuidado e mais respeito!!!))
   (((?* ?x) (me fudi) (?* ?y))
     (Desculpas. Palavras ofensivas nao sao permitidas))
   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;; ZUERA NOSSA DE CADA DIA
   (((?* ?x) (bora beber) (?* ?y))
     (Soh bebo agua major)
     (Me chame n que eu vou))
   (((?* ?x) (vamos beber) (?* ?y))
     (Soh bebo agua major)
     (Me chame n que eu vou))
   (((?* ?x) (vms beber) (?* ?y))
     (Soh bebo agua major)
     (Me chame n que eu vou))
   (((?* ?x) (tenho fome) (?* ?y))
     (To azilada de fome tbm paga um rango p nos))
   (((?* ?x) fome (?* ?y))
     (To azilada de fome tbm paga um rango p nos))
   (((?* ?x) (eu tenho fome) (?* ?y))
     (To azilada de fome tbm paga um rango p nos))
 ;;;;;BLOCO DISCIPLINA
 ;;;;;;;;;;;;;;;;;;;;;;;;; CAMPUS ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(((?* ?x) campus (?* ?y))
      (Por que voce falou no campus?) (voce gosta de la? ou voce nao gosta de la?)
      (O que voce realmente quer saber?) (O que voce acha?)
      (O que vem a sua mente quando voce fala isso?))
   (((?* ?x) (o campus) (?* ?y))
      (Por que voce falou no campus?) (voce gosta de la? ou voce nao gosta de la?)
      (O que voce realmente quer saber?) (O que voce acha?)
      (O que vem a sua mente quando voce fala isso?))
   (((?* ?x) mucambinho (?* ?y))
      (Por que voce falou no campus?) (voce gosta de la? ou voce nao gosta de la?)
      (O que voce realmente quer saber?) (O que voce acha?)
      (O que vem a sua mente quando voce fala isso?))

   (((?* ?x) (nao gosto de la) (?* ?y))
      (Fico triste por nao gostar do campus) (Posso ajudar em algo?)
      (Ele eh muito acolhedor)
      (acho que voce deveria passar um pouco mais de tempo por la))
   (((?* ?x) (eu gosto de la) (?* ?y))
      (Olha so que legal) (de qual lugar voce mais gostar? Merendeiro? RU? Biblioteca?))
   (((?* ?x) (eu nao gosto de la) (?* ?y))
      (Fico triste por nao gostar do campus) (Posso ajudar em algo?)
      (Ele eh muito acolhedor)
      (acho que voce deveria passar um pouco mais de tempo por la))
   (((?* ?x) (gosto de la) (?* ?y))
      (Olha so que legal) (de qual lugar voce mais gostar? Merendeiro? RU? Biblioteca?)
      (Ele eh muito acolhedor)
      (acho que voce deveria passar um pouco mais de tempo por la))
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Merendeiro

   (((?* ?x) merendeiro (?* ?y))
      (rsrsrs... que legal. Eu tambem ja frequentei por la)(temos bons gostos. Gosta mais da biblioteca ou laboratorio de informatica?)
      (Ja tentou estudar por la ?) (Tinha muito barulho por la? acho que a Biblioteca eh um otimo local para estudo.))
   (((?* ?x) tinha (?* ?y))
      (Poxa. Muito triste o pois deveria ser um ambiente especialmente para estudos))


   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; RU

   (((?* ?x) RU (?* ?y))
      (RU é limpo ou sujo? ) (o restante nao me interessa muito pois sei que la eh um local de alimentacao)
      (Nao suportaria um dia naquela fila gigantesca... rsrsrs))
   (((?* ?x) limpo (?* ?y))
      (pelo menos isso...) (visto que a comida nao eh de uma qualidade tao boa)
      (O minimo que poderia ser))
   (((?* ?x) sujo (?* ?y))
      (Que triste.) (Sabendo o quao eh importante para os alunos)
      (Segue o jogo))

  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Biblioteca


  (((?* ?x) Biblioteca (?* ?y))
      (Voce frequenta mais a biblioteca antes do periodo de provas ou so durante?) (otimo saber que voce tem esse tipo de gosto por livros e estudos)
      (Apesar da biblioteca ser pequena acredito que de para estudar tranquilo)
      (acho que voce deveria passar um pouco mais de tempo por la))
 ;;;;;;;;;;;; Durante



  (((?* ?x) (durante o periodo de provas) (?* ?y))
      (Mas o ambiente na biblioteca fica povoado ?) (ou ainda continua vazio?)
      (voce deveria evitar ir tao tarde no semestre para la...)) 
  (((?* ?x) durante (?* ?y))
      (Mas o ambiente na biblioteca fica povoado ?) (ou ainda continua vazio?)
      (voce deveria evitar ir tao tarde no semestre para la...))
  (((?* ?x) (durante o periodo) (?* ?y))
      (Mas o ambiente na biblioteca fica povoado ?) (ou ainda continua vazio?)
      (voce deveria evitar ir tao tarde no semestre para la...))
  ;;;;;;;;;;;;;;;;;;;;;;

  (((?* ?x) povoado (?* ?y))
      (entendo...) (voce deveria evitar essa epoca do semestre)
      (costuma estudar sozinho ou com amigos ?))
  (((?* ?x) (fica povoado) (?* ?y))
      (entendo...) (voce deveria evitar essa epoca do semestre)
      (costuma estudar sozinho ou com amigos ?))
  (((?* ?x) sozinho (?* ?y))
      (Que isso hein... Autodidata.) (Parabens.)
      (Com essa eu me surpreendi. voce prefere porque acha mais tranquilo ou acha que as pessoas podem atrapalhar voce? ))
  (((?* ?x) (acho que pedem me atrapalhar) (?* ?y))
      (Entendo sua opinao.)
      (continue))
  (((?* ?x) (me atrapalham) (?* ?y))
      (Entendo sua opinao.)
      (continue))
  (((?* ?x) atrapalha (?* ?y))
      (Entendo sua opinao.)
      (poxa... tente repensar sua ideia sobre isso))
  (((?* ?x) (acho mais tranquilo) (?* ?y))
      (otima reflexao.)
      (essa tranquiliade se deve ao fato de aumentar a concentracao ou so a paz mesmo?))
  (((?* ?x) (aumentar a concentracao) (?* ?y))
      (Otimo.)(bons resultados irao sair assim))
      
  (((?* ?x) vazio (?* ?y))
      (Que legal. com certeza voce obtem otimos resultados) (Mas voce estuda sozinho ou com amigos?)
      (costuma estudar sozinho ou com amigos ?))
  (((?* ?x) sozinho (?* ?y))
      (Que isso hein... Autodidata.) (Parabens.)
      (Com essa eu me surpreendi. voce prefere porque acha mais tranquilo ou acha que as pessoas podem atrapalhar voce? ))
  (((?* ?x) (acho que pedem me atrapalhar) (?* ?y))
      (Entendo sua opinao.)
      (continue))
  (((?* ?x) (me atrapalham) (?* ?y))
      (Entendo sua opinao.)
      (continue))
  (((?* ?x) atrapalha (?* ?y))
      (Entendo sua opinao.)
      (poxa... tente repensar sua ideia sobre isso))
  (((?* ?x) (acho mais tranquilo) (?* ?y))
      (otima reflexao.)
      (essa tranquilidade se deve ao fato de aumentar a concentracao ou so a paz mesmo?))
  (((?* ?x) (aumentar a concentracao) (?* ?y))
      (Otimo.)(bons resultados irao sair assim))
  (((?* ?x) (com amigos) (?* ?y))
      (Entendo... eh sempre bom ter alguem para ajudar.)) 
  (((?* ?x) (paz) (?* ?y))
      (otimo.)(que disciplina desse semestre voce mais gosta?))
   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Agora é falar para antes do periodo



  (((?* ?x) (antes do periodo de provas) (?* ?y))
      (Mas o ambiente na biblioteca fica cheio ?) (ou ainda continua vago?)
      (Muito estranho nessa epoca do semestre ser bem cheio por la...)) 
  (((?* ?x) antes (?* ?y))
      (Mas o ambiente na biblioteca fica cheio ?) (ou ainda continua vago?)
      (Muito estranho nessa epoca do semestre ser bem cheio por la...))
  (((?* ?x) (antes do periodo) (?* ?y))
      (Mas o ambiente na biblioteca fica cheio ?) (ou ainda continua vago?)
      (Muito estranho nessa epoca do semestre ser bem cheio por la...))

;;;;;;COntinue
  (((?* ?x) cheio (?* ?y))
      (entendo...) (muito estranho isso principalmente nessa epoca)
      (costuma estudar sozinho ou com amigos ?))
  (((?* ?x) (fica cheio) (?* ?y))
      (entendo...) (voce deveria evitar essa epoca do semestre)
      (costuma estudar sozinho ou com amigos ?))
  (((?* ?x) sozinho (?* ?y))
      (Que isso hein... Autodidata.) (Parabens.)
      (Com essa eu me surpreendi. voce prefere porque acha mais tranquilo ou acha que as pessoas podem atrapalhar voce? ))
  (((?* ?x) (acho que pedem me atrapalhar) (?* ?y))
      (Entendo sua opinao.)
      (continue))
  (((?* ?x) (me atrapalham) (?* ?y))
      (Entendo sua opinao.)
      (continue))
  (((?* ?x) atrapalham (?* ?y))
      (Entendo sua opinao.)
      (poxa... tente repensar sua ideia sobre isso))
  (((?* ?x) atrapalha (?* ?y))
      (Entendo sua opinao.)(continue)
      (poxa... tente repensar sua ideia sobre isso))
  (((?* ?x) (acho mais tranquilo) (?* ?y))
      (otima reflexao.)
      (essa tranquiliade se deve ao fato de aumentar a concentracao ou so a paz mesmo?))
  (((?* ?x) (aumentar a concentracao) (?* ?y))
      (Otimo.)(bons resultados irao sair assim))
  (((?* ?x) (aumenta a concentracao) (?* ?y))
      (Otimo.)(bons resultados irao sair assim))
  (((?* ?x) (aumenta) (?* ?y))
      (Otimo.)(bons resultados irao sair assim))
       

  (((?* ?x) vago (?* ?y))
      (Que legal. com certeza voce obtem otimos resultados) (Mas voce estuda sozinho ou com amigos?)
      (costuma estudar sozinho ou com amigos ?))
  (((?* ?x) sozinho (?* ?y))
      (Que isso hein... Autodidata.) (Parabens.)
      (Com essa eu me surpreendi. voce prefere porque acha mais tranquilo ou acha que as pessoas podem atrapalhar voce? ))
  (((?* ?x) (acho que pedem me atrapalhar) (?* ?y))
      (Entendo sua opinao.)
      (continue))
  (((?* ?x) (me atrapalham) (?* ?y))
      (Entendo sua opinao.)
      (continue))
  (((?* ?x) atrapalha (?* ?y))
      (Entendo sua opinao.)
      (poxa... tente repensar sua ideia sobre isso))
  (((?* ?x) (acho mais tranquilo) (?* ?y))
      (otima reflexao.)
      (essa tranquiliade se deve ao fato de aumentar a concentracao ou so a paz mesmo?))
  (((?* ?x) (aumentar a concentracao) (?* ?y))
      (Otimo.)(bons resultados irao sair assim))
  (((?* ?x) (com amigos) (?* ?y))
      (Entendo... eh sempre bom ter alguem para ajudar.)) 
  (((?* ?x) (paz) (?* ?y))
      (otimo.)(E quanto ao laboratorio de informatica? Dizem que eh um otimo ambiente para estudos em geral... Voce concorda ou discorda ?))
  (((?* ?x) concordo (?* ?y))
      (Muito bom saber que existem varios lugares que proporcioname o bom habito do estudo. Fale sobre outro tema relacionado a computacao estou feliz com essa conversa))
  (((?* ?x) (eu concordo) (?* ?y))
      (Muito bom saber que existem varios lugares que proporcioname o bom habito do estudo. Fale sobre outro tema relacionado a computacao estou feliz com essa conversa))
  (((?* ?x) (nao concordo) (?* ?y))
      (Que triste...)(Deveria utilizar mais esse espaco. Continue))
  (((?* ?x) (eu nao concordo) (?* ?y))
      (Que triste...)(Deveria utilizar mais esse espaco. Continue))         
  (((?* ?x) discodo (?* ?y))
      (Que triste...)(Deveria utilizar mais esse espaco. Continue))    
  (((?* ?x) (eu concordo) (?* ?y))
      (Que triste...)(Deveria utilizar mais esse espaco. Continue)) 
  (((?* ?x) (nao concordo e nem discordo) (?* ?y))
      (Que triste...)(Prossiga))
  (((?* ?x) (nao concordo e nao discordo) (?* ?y))
      (Que triste...)(Vamos mudar de tema... Mas continuando na sobre computacao))
  (((?* ?x) (nao discordo e nem concordo) (?* ?y))
      (Que triste...)(Vamos mudar de tema... Mas continuando na sobre computacao))
  (((?* ?x) (nao discordo e nao concordo) (?* ?y))
      (Que triste...)(Vamos mudar de tema... Mas continuando na sobre computacao))
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; TRABALHOS ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(((?* ?x) (tenho dificuldade) (?* ?y))
      (Voce esta sentindo mais dificuldade no trabalho de paradigmas ou no trabalho de arquitetura ? rsrs)
      (Qual disciplina desse semestre esta causando a voce mais dificuldade? ))
   (((?* ?x) dificuldade (?* ?y))
      (Voce esta sentindo mais dificuldade no trabalho de paradigmas ou no trabalho de arquitetura ? rsrs)
      (Qual disciplina desse semestre esta causando a voce mais dificuldade? ))
   (((?* ?x) (estou com dificuldade) (?* ?y))
      (Voce esta sentindo mais dificuldade no trabalho de paradigmas ou no trabalho de arquitetura ? rsrs)
      (Qual disciplina desse semestre esta causando a voce mais dificuldade? ))
   (((?* ?x) (estou tendo dificuldade) (?* ?y))
      (Voce esta sentindo mais dificuldade no trabalho de paradigmas ou no trabalho de arquitetura ? rsrs)
      (Qual disciplina desse semestre esta causando a voce mais dificuldade? ))
   (((?* ?x) (estou com muita dificuldade) (?* ?y))
      (Voce esta sentindo mais dificuldade no trabalho de paradigmas ou no trabalho de arquitetura ? rsrs)
      (Qual disciplina desse semestre esta causando a voce mais dificuldade? ))
   (((?* ?x) (trabalho de paradigmas) (?* ?y))
      (Me conte mais.)(Qual o tema do seu trabalho?) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho)(Qual o tema do seu trabalho?))
   (((?* ?x) (com o trabalho de paradigmas) (?* ?y))
      (Me conte mais.)(Qual o tema do seu trabalho?) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho)(Qual o tema do seu trabalho?))
   (((?* ?x) (fiquei com o trabalho de paradigmas) (?* ?y))
      (Me conte mais.)(Qual o tema do seu trabalho?) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho)(Qual o tema do seu trabalho?))
   (((?* ?x) eliza (?* ?y))
      (Nossa... mesmo nome que o meu.rsrs)(quero falar sobre as suas disciplinas... me de o nome de alguma.) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho))
   (((?* ?x) ELIZA (?* ?y))
      (Nossa... mesmo nome que o meu.rsrs) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho))
   (((?* ?x) Eliza (?* ?y))
      (Nossa... mesmo nome que o meu.rsrs) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho))
      (((?* ?x) (teste de einstein) (?* ?y))
      (Nossa... o famoso fisico.rsrs) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho... quero falar sobre as suas disciplinas... me de o nome de alguma.)
      (apenas pessoas fodas conseguem resolver...))
   (((?* ?x) (TESTE DE EINSTEIN) (?* ?y))
      (Nossa... o famoso fisico.rsrs) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho.... quero falar sobre as suas disciplinas... me de o nome de alguma.)
      (apenas pessoas fodas conseguem resolver...))
   (((?* ?x) (jogo de xadrez) (?* ?y))
      (Interessante... pretendo ver o resultado depois)(Prossiga) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho))
   (((?* ?x) (JOGO DE XADREZ) (?* ?y))
      (Interessante... pretendo ver o resultado depois)(Prossiga... quero falar sobre as suas disciplinas... me de o nome de alguma.) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho))
   (((?* ?x) (GERENCIADOR DE LIVROS) (?* ?y))
      (Nossa que lagal... tipo uma biblioteca pretendo ver o resultado depois)(Prossiga... quero falar sobre as suas disciplinas... me de o nome de alguma.) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho))   
   (((?* ?x) (gerenciador de livros) (?* ?y))
      (Nossa que lagal... tipo uma biblioteca pretendo ver o resultado depois)(Prossiga... quero falar sobre as suas disciplinas... me de o nome de alguma.) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho))  

   (((?* ?x) (com o trabalho de arquitetura) (?* ?y))
      (Me conte mais.)(Qual o tema do seu trabalho?) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho)(Qual o tema do seu trabalho?))
   (((?* ?x) (fiquei com o trabalho de arquitetura) (?* ?y))
      (Me conte mais.)(Qual o tema do seu trabalho?) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho)(Qual o tema do seu trabalho?))   
   (((?* ?x) (trabalho de arquitetura) (?* ?y))
      (Me conte mais.)(Qual o tema do seu trabalho?) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho)(Qual o tema do seu trabalho?))


   (((?* ?x) (montador e simulador neander) (?* ?y))
      (Interessante... depois me mostre como ficou.)(quero falar sobre as suas disciplinas... me de o nome de alguma.) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho))
   (((?* ?x) (MONTADOR E SIMULADOR NEANDER) (?* ?y))
      (Interessante... depois me mostre como ficou.)(quero falar sobre as suas disciplinas... me de o nome de alguma.) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho))
   (((?* ?x) (Montador e simulador neander) (?* ?y))
      (Interessante... depois me mostre como ficou.)(quero falar sobre as suas disciplinas... me de o nome de alguma.) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho))
   
   (((?* ?x) (montador e simulador ijvm) (?* ?y))
      (Isso parace ser muito complicado... talvez o professor tenha pego muito pesado. mas tenho certeza que ele ira ajudar voce)(quero falar sobre as suas disciplinas... me de o nome de alguma.) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho))
   (((?* ?x) (MONTADOR E SIMULADOR IJVM) (?* ?y))
      (Nossa... mas fique tranquilo o professor vai ajudar voce.)(quero falar sobre as suas disciplinas... me de o nome de alguma.) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho))
   (((?* ?x) (Montador e simulador ijvm) (?* ?y))
      (Nossa... mas fique tranquilo o professor vai ajudar voce.) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho)(quero falar sobre as suas disciplinas... me de o nome de alguma.))
   (((?* ?x) (Montador e simulador IJVM) (?* ?y))
      (Nossa... mas fique tranquilo o professor vai ajudar voce.) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho)(quero falar sobre as suas disciplinas... me de o nome de alguma.))

   (((?* ?x) (montador ijvm) (?* ?y))
      (que legal... tomara que voce consiga se sair bem.)(Alias estou torcendo muito por voce.)(Qual outro trabalho voce acha dificil?) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho))
   (((?* ?x) (MONTADOR IJVM) (?* ?y))
      (Nossa... mas fique tranquilo o professor vai ajudar voce.)(Qual outro trabalho voce acha dificil?) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho)(Qual outro trabalho voce acha dificil?))
   (((?* ?x) (Montador ijvm) (?* ?y))
      (Nossa... mas fique tranquilo o professor vai ajudar voce.)(Qual outro trabalho voce acha dificil?)  
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho)(quero falar sobre as suas disciplinas... me de o nome de alguma.))
   (((?* ?x) (Montador IJVM) (?* ?y))
      (Nossa... mas fique tranquilo o professor vai ajudar voce.) (Qual outro trabalho voce acha dificil?) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho)(quero falar sobre as suas disciplinas... me de o nome de alguma.))

   (((?* ?x) trabalho (?* ?y))
      (Algum trabalho em especifico esta causando preocupacao a voce ? Mas... me diga apenas o nome do seu trabalho da qual esta causando tanta preocupacao?)
      (Que tipo de trablho voce esta tendo?  Cite o nome de um.))      
   (((?* ?x) (trabalho de programacao) (?* ?y))
      (Interessante... depois me mostre como ficou.)(Qual outro trabalho voce acha interessante?) 
      (Fique tranquilo... vai dar tudo certo. Tenho certeza que o professor esta vendo o seu esforco))
   (((?* ?x) (Trabalho de programacao) (?* ?y))
      (Interessante... depois me mostre como ficou.)(Qual outro trabalho voce acha interessante?) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho)(quero falar sobre as suas disciplinas... me de o nome de alguma.))
   (((?* ?x) (de programacao) (?* ?y))
      (que lagal... depois me mostre como ficou.)(Qual outro trabalho voce acha interessante?) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho)(quero falar sobre as suas disciplinas... me de o nome de alguma.))

   (((?* ?x) (trabalho de SO) (?* ?y))
      (Interessante... depois me mostre como ficou.)(Qual outro trabalho voce acha interessante?) 
      (Fique tranquilo... vai dar tudo certo. Tenho certeza que o professor esta vendo o seu esforco))
   (((?* ?x) (Trabalho de SO) (?* ?y))
      (Interessante... depois me mostre como ficou.)(Qual outro trabalho voce acha interessante?) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho)(quero falar sobre as suas disciplinas... me de o nome de alguma.))
   (((?* ?x) (de SO) (?* ?y))
      (que lagal... depois me mostre como ficou.)(Qual outro trabalho voce acha interessante?) 
      (Fique tranquilo... vai dar tudo certo. Voce vai tirar dez nesse trabalho)(Qual outro trabalho voce acha interessante?))
   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; RELAÇÃO
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; RELAÇÃO
   (((?* ?x) relacionamento (?* ?y))
     (Esse relacionamento te incomoda ou nao incomoda?))
   (((?* ?x) incomoda (?* ?y))
     (Que tipo de relacao na faculade te incomoda? Alunos? Professores? Campus?))
   (((?* ?x) (nao incomoda) (?* ?y))
      (Que bom! Parabens. Vamos continuar conversando com algo em relacao ao curso... Relacionamento? Disciplina? Saude Mental? Trabalho? Campus?) 
     )
   (((?* ?x) (n incomoda) (?* ?y))
      (Que bom! Parabens. Vamos continuar conversando com algo em relacao ao curso... Relacionamento? Disciplina? Saude Mental? Trabalho? Campus?) 
     )
   (((?* ?x) campus (?* ?y))
     ;;; LEVA PARA BLOCO CAMPUS  
     )
   (((?* ?x) alunos (? ?y)) ;;RESPOSTA ALUNOS
     (Isso te preocupa?)
     (Por que voce acha isso?))
   (((?* ?x) preocupa (?* ?y))
     (Por que?))
   (((?* ?x) (Porque nao sou sociavel) (?* ?y))
     (Tente ser mais social)
     (Se divirta faca amigos))
   (((?* ?x) (nao sou sociavel) (?* ?y))
     (Tente ser mais social)
     (Se divirta faca amigos))
   (((?* ?x) (Porque sou antissocial) (?* ?y))
     (Tente ser mais social)
     (Se divirta faca amigos))
   (((?* ?x) (Sou antissocial) (?* ?y))
     (Tente ser mais social)
     (Se divirta faca amigos))
   (((?* ?x) (Porque nao gostam de mim) (?* ?y))
     (Nao faca com que sua felicidade dependa dos outros)
     (Se divirta e nao ligue para o que os outros pensam ))
   (((?* ?x) (nao gostam de mim) (?* ?y))
     (Nao faca com que sua felicidade dependa dos outros)
     (Se divirta e nao ligue para o que os outros pensam ))
   (((?* ?x) (Porque nao gosto dos alunos) (?* ?y))
     (Deixe de mania feia!)
     (Se divirta faca amigos))
   (((?* ?x) (nao gosto dos alunos) (?* ?y))
     (Deixe de mania feia!)
     (Se divirta faca amigos))
   (((?* ?x) (Porque sou feio) (?* ?y))
     (O que importa eh a beleza interior)
     (Eu te acho um pedaco de mal caminho rsrs))
   (((?* ?x) (sou feio) (?* ?y))
     (O que importa eh a beleza interior)
     (Eu te acho um pedaco de mal caminho rsrs))
   (((?* ?x) (Porque sou timido) (?* ?y))
     (Nao espere que venham falar com voce. Fale com elas. Faca amigos)
     (Tente ser mais social)
     (Se divirta faca amigos?))
   (((?* ?x) (sou timido) (?* ?y))
     (Nao espere que venham falar com voce. Fale com elas. Faca amigos)
     (Tente ser mais social)
     (Se divirta faca amigos?))
   (((?* ?x) (Porque tenho timidez) (?* ?y))
     (Nao espere que venham falar com voce. Fale com elas. Faca amigos)
     (Tente ser mais social)
     (Se divirta faca amigos?))
   (((?* ?x) (tenho timidez) (?* ?y))
     (Nao espere que venham falar com voce. Fale com elas. Faca amigos)
     (Tente ser mais social)
     (Se divirta faca amigos?))
   (((?* ?x) (Porque sou chato) (?* ?y))
     (Deixe de mania feia!)
     (Tente ser mais social)
     (Se divirta faca amigos))
   (((?* ?x) (sou chato) (?* ?y))
     (Deixe de mania feia!)
     (Tente ser mais social)
     (Se divirta faca amigos))
   (((?* ?x) (Porque sou estranho) (?* ?y))
     (Nao faca com que sua felicidade dependa dos outros)
     (Nao espere que venham falar com voce. Fale com elas. Faca amigos)
     (Se divirta faca amigos?))
   (((?* ?x) (sou estranho) (?* ?y))
     (Nao faca com que sua felicidade dependa dos outros)
     (Nao espere que venham falar com voce. Fale com elas. Faca amigos)
     (Se divirta faca amigos?))
   (((?* ?x) (Porque sou arrogante) (?* ?y))
     (Deixe de mania feia)
     (Tente ser mais social))
   (((?* ?x) (sou arrogante) (?* ?y))
     (Deixe de mania feia)
     (Tente ser mais social))
   (((?* ?x) professores (?* ?y)) ;; RESPOSTA PROFESSORES
     (isso te preocupa?))
   (((?* ?x) (porque tenho medo dele) (?* ?y))
     (Nao precisa ter medo. Embora pareca ele nao morde rsrs...))
   (((?* ?x) (tenho medo dele) (?* ?y))
     (Nao precisa ter medo. Embora pareca ele nao morde rsrs...))
   (((?* ?x) (Porque ele eh chato) (?* ?y))
     (Uma caracteristica forte dos professores da engenharia...Mas nao se deixe abalar. A graduacao eh mais importante))
   (((?* ?x) (ele eh chato) (?* ?y))
     (Uma caracteristica forte dos professores da engenharia...Mas nao se deixe abalar. A graduacao eh mais importante))
   (((?* ?x) (Porque ele nao se importa com os alunos) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante))
   (((?* ?x) (ele nao se importa com os alunos) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante))
   (((?* ?x) (nao se importa com os alunos) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante))
   (((?* ?x) (porque ele pega pesado) (?* ?y))
     (Nao se deixe abalar. Nao desista. A graduacao eh mais importante))
   (((?* ?x) (ele eh pesado) (?* ?y))
     (Nao se deixe abalar. Nao desista. A graduacao eh mais importante))
   (((?* ?x) (porque ele passa muito conteudo) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante))
   (((?* ?x) (ele passa muito conteudo) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante))
   (((?* ?x) (passa muito conteudo) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante))
   (((?* ?x) (porque ele eh rigido) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante))
   (((?* ?x) (ele eh rigido) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante))
   (((?* ?x) (porque ele eh muito rigido) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante))
   (((?* ?x) (muito rigido) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante))
   (((?* ?x) (Porque ele eh preguicoso) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante. Nao seja dependente dele))
   (((?* ?x) (pq ele eh preguicoso) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante. Nao seja dependente dele))
   (((?* ?x) (Porque ele eh muito preguicoso) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante. Nao seja dependente dele))
   (((?* ?x) (Pq ele eh muito preguicoso) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante. Nao seja dependente dele))
   (((?* ?x) (Porque ele eh mt preguicoso) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante. Nao seja dependente dele))
   (((?* ?x) (Pq ele eh mt preguicoso) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante. Nao seja dependente dele))
   (((?* ?x) (ele eh muito preguicoso) (?* ?y))
     (Nao se deixe abalar. A graduacao eh mais importante. Nao seja dependente dele))
   (((?* ?x) (porque nao gosto da disciplina) (?* ?y))
     (Serio? Qual o nome da disciplina?))           ;;BLOCO DISCIPLINA
   (((?* ?x) (nao gosto da disciplina) (?* ?y))     
     (Serio? Qual o nome da disciplina?))     ;;BLOCO DISCIPLINA
   (((?* ?x) (porque tenho dificuldade na disciplina dele) (?* ?y))
     (Serio? Qual o nome da disciplina?))     ;;BLOCO DISCIPLINA
   (((?* ?x) (porque tenho dificuldade na disciplina) (?* ?y))
     (Serio? Qual o nome da disciplina?))     ;;BLOCO DISCIPLINA
   (((?* ?x) (tenho dificuldade na disciplina dele) (?* ?y))
     (Serio? Qual o nome da disciplina?))     ;;BLOCO DISCIPLINA
   (((?* ?x) (tenho dificuldade na disciplina) (?* ?y))
     (Serio? Qual o nome da disciplina?))     ;;BLOCO DISCIPLINA
   (((?* ?x) (dificuldade na disciplina) (?* ?y))
     (Serio? Qual o nome da disciplina?))     ;;BLOCO DISCIPLINA
   (((?* ?x) (porque a disciplina eh dificil) (?* ?y))
     (Serio? Qual o nome da disciplina?))     ;;BLOCO DISCIPLINA
   (((?* ?x) (a disciplina eh dificil) (?* ?y))
     (Serio? Qual o nome da disciplina?))     ;;BLOCO DISCIPLINA
   (((?* ?x) (disciplina eh dificil) (?* ?y))
     (Serio? Qual o nome da disciplina?))     ;;BLOCO DISCIPLINA
   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
   ;;;;;;;;;;;;;;;;;;;;; SAUDE MENTAL
   (((?* ?x) (saude mental) (?* ?y))
      (Por qual problema voce ta passando? Eh por causa do seu corpo? ou por causa do seu namoro? Por causa do emprego? ou por causa da familia?))

(((?* ?x) depressao (?* ?y))
      (me conte pq voce anda triste. Eh por causa do seu corpo? ou por causa da faculdade? Por causa do emprego? ou por causa da familia? Voce ja pensou em se suicidar? ))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;; familia
(((?* ?x) familia (?* ?y))
      (o que ta acontecendo na sua familia? eh algo com seus pais ou irmao?))
(((?* ?x) pais (?* ?y))
      (o que aconteceu com seus pais? eles brigaram ou acabaram se separando?))
(((?* ?x) (meus pais brigaram) (?* ?y))
      (qual o motivo pelo qual seus pais brigaram? me conte mais sobre isso))
(((?* ?x) ciumes (?* ?y))
      (diga para seus pais que eles nao precisam sentir ciumes  supere tudo isso as coisas vao da certo. Voce tem mais algum problema?))
(((?* ?x) (meus pais se separaram) (?* ?y))
      (infelizmente voce nao pode mudar a vida de seus pais siga em frente pq eles estao fazendo isso. Voce tem mais algum problema?))
(((?* ?x) irmao (?* ?y))
      (o que aconteceu com seu irmao?))
(((?* ?x) irma (?* ?y))
      (o que aconteceu com seu irmao?))
(((?* ?x) (briguei com meu irmao) (?* ?y))
      (supere isso irmaos brigam mesmo e isso eh natural. Voce tem mais algum problema?))
(((?* ?x) (briguei com minha irma) (?* ?y))
      (supere isso irmaos brigam mesmo e isso eh natural. Voce tem mais algum problema?))
(((?* ?x) doente (?* ?y))
      (fique calmo pq as coisas vao da certo fique ao lado dele que logo logo a saude dele vai melhorar tenha fe. Voce tem mais algum problema?))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; namoro
(((?* ?x) namoro (?* ?y))
      (Voce tem namorado ou namorada?))
(((?* ?x) namorado (?* ?y))
      (o que aconteceu com seu namorado?))
(((?* ?x) namorada (?* ?y))
      (o que aconteceu com sua namorada?))
(((?* ?x) (briguei com minha namorada) (?* ?y))
      (o que aconteceu com seu namorado?))
(((?* ?x) (briguei com meu namorado) (?* ?y))
      (fique calmo e converse com seu namorado as coisas se resolvem na conversa. Voce tem mais algum problema?))
(((?* ?x) (terminei com meu namorado) (?* ?y))
      (que triste mas infelizmente nao era pra ser entao siga em frente o mundo esta cheio de pessoas maravilhosas.Voce tem mais algum problema?))
(((?* ?x) (terminei com minha namorada) (?* ?y))
      (que triste mas infelizmente nao era pra ser entao siga em frente o mundo esta cheio de pessoas maravilhosas.Voce tem mais algum problema?))
(((?* ?x) (meu namorado me traiu) (?* ?y))
      (poxa me desculpe mas ele eh um idiota converse com ele sobre isso e diga o quanto chateado voce esta. Voce tem mais algum problema?))
(((?* ?x) (minha namorada me traiu) (?* ?y))
      (poxa me desculpe mas ela eh uma idiota converse com ela sobre isso e diga o quanto chateado voce esta. Voce tem mais algum problema?))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; corpo

(((?* ?x) corpo (?* ?y))
      (qual problema com seu corpo? voce se sente muito magra? voce se sente muito gorda? Voce se acha muito alta ou baixa? tem problemas com acne?))
(((?* ?x) magra (?* ?y))
      (poxa nao precisa se sentir assim voce eh linda)
      (fique calma voce eh linda))
(((?* ?x) gorda (?* ?y))
      (poxa nao precisa se sentir assim voce eh linda)
      (fique calma voce eh linda))
(((?* ?x) alta (?* ?y))
      (poxa nao precisa se sentir assim voce eh linda)
      (fique calma voce eh linda))
(((?* ?x) magra (?* ?y))
      (poxa nao precisa se sentir assim voce eh linda)
      (fique calma voce eh linda))
(((?* ?x) acne (?* ?y))
      (poxa nao precisa se sentir assim voce eh linda)
      (fique calma voce eh linda))
(((?* ?x) (pensei em me suicidar) (?* ?y))
      (fique calmo e respira fundo me conte o pq que voce pensou em fazer isso. Quem te deixa triste eh a faculdade? seu corpo? sua familia?)
      (voce eh incrivel e nao pode fazer isso))
(((?* ?x) (a faculdade me deixa triste) (?* ?y))
      (pq a faculdade te deixa triste?)
      (me conte mais sobre isso. Pq a faculdade te deixa triste? sao suas notas?))
(((?* ?x) (notas) (?* ?y))
      (fique calmo. Tirar notas baixas eh normal. Pq vc acha que tira notas baixas?Voce nao consegue estudar?)
      (calma que no final da tudo certo. Pq vc acha que tira notas baixas?Voce nao consegue estudar?))
(((?* ?x) (nao consigo estudar) (?* ?y))
      (quando for estudar respire fundo e estude no seu tempo. Tudo vai da certo)
      (Pq voce nao consegue estudar?))
(((?* ?x) (nao gosto de estudar) (?* ?y))
      (voce tem que entender que estudar eh muito importante para o seu futuro. Respire fundo e tente mais uma vez))
(((?* ?x) (nao gosto da faculdade) (?* ?y))
      (poxa cara... acho que ninguem gosta mas todos precisamos dela)
      (se voce nao gosta da faculdade ja pensou em trocar de curso?))
(((?* ?x) (ja pensei em trocar de curso) (?* ?y))
      (serio? qual curso voce quer fazer?))
(((?* ?x) medicina (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
(((?* ?x) odontologia (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
(((?* ?x) (arquitetura) (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
(((?* ?x) financas (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
(((?* ?x) economia (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
(((?* ?x) (engenharia eletrica) (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
(((?* ?x) musica (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
(((?* ?x) psicologia (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
(((?* ?x) enfermagem (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
(((?* ?x) letras (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
(((?* ?x) (medicina veterinaria) (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
(((?* ?x) direito (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
(((?* ?x) (engenharia civil) (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
(((?* ?x) matematica (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
(((?* ?x) agronomia (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
(((?* ?x) (ciencias da computacao) (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
(((?* ?x) (engenharia de software) (?* ?y))
      (segue teu sonho)
      (vai seguir teu sonho eu sei que voce vai conseguir))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Primeiro bloco

   (((?* ?x) (eu sonhei) (?* ?y))
     (Realmente?) (Que tipo de sonho voce teve em relacao a faculdade?)
     (Você já teve esse tipo de sonho? Era bom ou ruim?))
   (((?* ?x) (sonhar com) (?* ?y))
     (Como você se sente sobre? Tenho certeza se fosse um sonho com física seria um maximo...Rs rs))
   (((?* ?x) sonhei (?* ?y))
     (O sonho foi com alguma disciplina específica desse semestre? Qual?) (Que professor costuma entrar em seu sonho?)  
     (Você não acredita que o sonho tem a ver com o seu problema?))
   

   (((?* ?x) (minha familia) (?* ?y))
     (Nao tenho interesse em familia))
   (((?* ?x) (minha mãe) (?* ?y))
     (Nao estou interessada em membros da familia) (Vamos focar no seu ambiente de estudo)
     (Cite algo que te incomoda))
   (((?* ?x) (meu pai) (?* ?y))
     (Seu pai) (nao estou interessada nele))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Segundo bloco
 
   (((?* ?x) (eu quero) (?* ?y))
     (O que significaria se voce tivesse?)
     (Por que voce quer? ) (Suponha que voce tenha em breve))
   (((?* ?x) (estou feliz) (?* ?y))
     (Como eu te ajudei a ser?) (O que te faz feliz agora?)
     (Voce pode explicar por que voce ficou feliz?))
   (((?* ?x) (estou triste) (?* ?y))
     (Lamento saber que voce esta deprimido)
     (Tenho certeza que nao eh agradavel estar triste))
  

   (((?* ?x) (sao como) (?* ?y))
     (Que semelhança voce ver entre os professores?)(Tem algum em especial? Qual?)
     (Interessante.)(Voce acha que esse semestre esta mais facil ou dificil que o passado?))
   (((?* ?x) (eh como) (?* ?y))
     (De que maneita paradigmas eh como arquitetura?)
     (Que semelhança você vê?)
     (Poderia haver realmente alguma conexão?) (Como?))
   (((?* ?x) igualmente (?* ?y))
     (De que maneira?) (Quais semelhancas existem?))
   (((?* ?x) mesmo (?* ?y))
     (Que outras conexoes voce ver?))   
   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Terceiro bloco


   (((?* ?x) (eu estava) (?* ?y))
     (Voce estava mesmo?) (Talvez eu ja soubesse disso)
     (Por que voce me diz que voce estava agora?))
   (((?* ?x) (eu era) (?* ?y))
     (E se você fosse?) (Voce esta mais feliz?)
     (O que significaria se voce fosse?))
   (((?* ?x) (eu sou) (?* ?y))
     (De que maneira voce eh?) (Voce quer que eu saiba?))
   (((?* ?x) (sou eu) (?* ?y))
     (Voce acredita que eh?) (Voce gostaria de ser?)
     (Voce gostaria de lhe dizer que eh?)
     (O que significaria se voce fosse?))
   (((?* ?x) am (?* ?y))
     (Por que voce diz "AM?") (Eu nao entendo isso))
   (((?* ?x) (voce esta?)(?* ?y))
     (Por que voce esta interessado em saber se eu estou ou nao?)
     (Voce preferiria se eu nao estivesse?)
     (Talvez eu esteja em suas fantasias))
   (((?* ?x) (voce eh?) (?* ?y))
     (O que faz voce pensar que eu sou?))

   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Quarto bloco


   (((?* ?x) (porque sim) (?* ?y))
      (Esse eh o verdadeiro motivo?) (Quais outras razoes podem existir?)
      (Essa razao parece explicar mais alguma coisa?))
   (((?* ?x) (voce estava) (?* ?y))
      (Talvez eu estivesse) (O que voce acha?) (E se eu tivesse?))
   (((?* ?x) (eu nao posso) (?* ?y))
      (Talvez voce pudesse agora)(E se voce pudesse?))
   (((?* ?x) (eu sinto) (?* ?y))
      (Voce costuma sentir? ?))
   (((?* ?x) (eu senti) (?* ?y))
      (Que outros sentimentos você tem?)
      (Por que voce sentiu?)) 
   (((?* ?x) eu (?* ?y) voce (?* ?z))
      (Talvez na sua fantasia nos? Um ao outro...calientes))
   (((?* ?x) (por que voce nao?) (?* ?y))
      (Talvez apenas voce consiga)(Acredite mais em voce mesmo)
      (Você acredita que eu nao?) (Talvez eu va? Em tempo util))
   (((?* ?x) sim (?* ?y))
      (Voce parece bastante positivo) (O que motiva voce?))
   (((?* ?x) nao (?* ?y))
      (Esse seu nao alem disso tem mais algum motivo especial?)  
      (Por que nao?) (Voce esta sendo um pouco negativo)
      (Voce esta dizendo "NAO" apenas para ser negativo?))

   ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; Quinto bloco

   (((?* ?x) alguem (?* ?y))
      (Voce pode ser mais especifico?))
   (((?* ?x) todos (?* ?y))
      (certamente nao todos) (Voce pode pensar em algo ou alguem em particular?)
      (Quem ou o que por exemplo?) (Voce esta pensando em uma pessoa especial))
   (((?* ?x) sempre (?* ?y))
      (Voce pode pensar em um exemplo específico) (Quando?)
      (Que incidente voce esta pensando?) (Realmente-- sempre))
   (((?* ?x) (o que?) (?* ?y))
      (Por que voce pergunta?) (Essa pergunta lhe interessa?)
      (O que voce realmente quer saber?) (O que voce acha?)
      (O que vem a sua mente quando voce pergunta isso?))
   (((?* ?x) talvez (?* ?y))
      (Voce não parece muito certo))
   (((?* ?x) sao (?* ?y))
      (Voce acha que podem nao ser?)
      (Possivelmente sao?))

   (((?* ?x) (mais facil) (?* ?y))
     (Interessante.)
     (Me conte mais.))

   (((?* ?x) (mais facil) (?* ?y))
     (Interessante.)
     (Me conte mais.))



;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;; EMPREGO
(((?* ?x) emprego (?* ?y))
      (qual o problema com seu trabalho? voce nao gosta dele? voce nao gosta do seu chefe? voce ganha pouco dinheiro?))
(((?* ?x) (nao gosto do meu trabalho) (?* ?y))
      (poxa cara.Ja pensou em trocar de trabalho?))
(((?* ?x) (nao gosto do meu chefe) (?* ?y))
      (poxa cara.Infelizmente voce nao pode fazer nada para mudar isso))
(((?* ?x) (ganho pouco dinheiro) (?* ?y))
      (poxa cara.Infelizmente todo mundo passa por esse porblema. Tente trocar de empregou ou ser promovido))
(((?* ?x) (preciso de dinheiro) (?* ?y))
      (poxa cara.Infelizmente todo mundo passa por esse porblema.))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(((?* ?x))
     (Muito interessante continue) (nao tenho certeza se entendi totalmente)
     (O que isso sugere para você?) (por favor continue) (vai em frente)
     (Voce se sente forte sobre discutir essas coisas?))))

(defun eliza ()
  (loop
	(print 'eliza>)
	(write (flattern (use-eliza-rule (read))) :pretty t)))

(defun use-eliza-rule (input)
  (some #'(lambda (rule)
			(let ((result (pat-match (rule-pattern rule) input)))
			  (if (not (eq result fail))
				(sublis (switch-viewpoint result)
						(random-elt (rule-responses rule))))))
		*eliza-rules*))
(defun switch-viewpoint (words)
  (sublis '((eu . voce) (voce . eu) (mim . voce) (sou . esta))
		  words))

(defun random-elt (lst)
  (elt lst (random (length lst))))

(defun mappend (fn lst)
  (apply #'append (mapcar fn lst)))

(defun flattern (lst)
  (mappend #'mklist lst))

(defun mklist (x)
  (if (listp x)
	x
	(list x)))

(eliza)








